import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

const PUBLIC_PATHS = [
  "/login",
  "/login/mfa",
  "/login/mfa-setup",
  "/login/set-password",
  "/auth/callback",
];

const PUBLIC_API_PREFIXES = ["/api/auth/"];

function isPublicPath(pathname: string) {
  if (PUBLIC_PATHS.includes(pathname)) return true;
  return PUBLIC_API_PREFIXES.some((prefix) => pathname.startsWith(prefix));
}

/**
 * Refreshes the Supabase session cookie on every request and enforces:
 * unauthenticated -> /login, MFA-pending -> the right challenge/setup
 * page, and admin-only paths -> role check against users_gyms.
 */
export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({ request });

  const url = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_ANON_KEY;

  if (!url || !anonKey) {
    throw new Error("Supabase server environment variables are not configured");
  }

  const supabase = createServerClient(url, anonKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
        supabaseResponse = NextResponse.next({ request });
        cookiesToSet.forEach(({ name, value, options }) =>
          supabaseResponse.cookies.set(name, value, {
            ...options,
            httpOnly: true,
            secure: true,
            sameSite: "strict",
          })
        );
      },
    },
  });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { pathname } = request.nextUrl;
  const isPublic = isPublicPath(pathname);

  if (!user) {
    if (isPublic) return supabaseResponse;
    const loginUrl = new URL("/login", request.url);
    return NextResponse.redirect(loginUrl);
  }

  const { data: aal } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
  const mfaChallengePending = !!aal && aal.currentLevel !== aal.nextLevel;

  if (mfaChallengePending) {
    // /api/auth/* routes (e.g. mfa/verify) validate the session themselves
    // and must stay reachable while a challenge is outstanding — redirecting
    // them here would break the very requests needed to clear the challenge.
    if (pathname === "/login/mfa" || isPublic) return supabaseResponse;
    return NextResponse.redirect(new URL("/login/mfa", request.url));
  }

  // A one-time password generated by an admin (see createOwnerAccount) is
  // otherwise permanent — there's no invite-link flow forcing a real
  // password choice, so this app_metadata flag stands in for it. Only the
  // admin API can set app_metadata, so the owner can't clear this
  // themselves; /api/auth/set-password clears it server-side once they've
  // actually chosen their own password. Deliberately narrower than the
  // isPublic escape used elsewhere in this function — that list includes
  // /login/mfa-setup and /login/mfa, which this gate must NOT let through,
  // otherwise someone could sidestep the password change by navigating
  // straight to either of those (this is also why resolveNextAuthStep's
  // equivalent check can't be relied on alone: it only governs the initial
  // post-login redirect, not direct navigation afterward).
  if (user.app_metadata?.must_change_password) {
    const allowed = pathname === "/login/set-password" || pathname === "/login" || pathname.startsWith("/api/auth/");
    if (allowed) return supabaseResponse;
    return NextResponse.redirect(new URL("/login/set-password", request.url));
  }

  const { data: gymRows } = await supabase
    .from("users_gyms")
    .select("role")
    .eq("user_id", user.id)
    .limit(1);
  const role = gymRows?.[0]?.role;

  // MFA is mandatory for every role, not just admin — found 2026-07-27 when
  // a freshly created owner test account reached the dashboard with no MFA
  // prompt at all. This used to be gated behind `role === "admin"`; Supabase's
  // own AAL check can't catch a no-factors-enrolled account on its own
  // (nextLevel only exceeds currentLevel once a factor exists), so without an
  // unconditional check here, every non-admin role skipped MFA setup entirely.
  const { data: factors } = await supabase.auth.mfa.listFactors();
  if (!factors?.totp.length) {
    // Let a brand-new invited/recovering account set a password first —
    // they'll be bounced here again on their next navigation regardless.
    // Also let /api/auth/* through: it's what set-password and
    // mfa/enroll|verify run on, and redirecting those breaks the flow
    // that's supposed to clear this very gate.
    if (pathname === "/login/mfa-setup" || pathname === "/login/set-password" || isPublic) {
      return supabaseResponse;
    }
    return NextResponse.redirect(new URL("/login/mfa-setup", request.url));
  }

  // Fully authenticated (and MFA-compliant) at this point — bounce away
  // from the login flow. set-password stays reachable even here: recovery
  // for an account that already has MFA enrolled needs a completed AAL2
  // challenge before Supabase will accept the new password, so by the time
  // this gate is reached the user is "fully authenticated" but still needs
  // this exact page to finish what the recovery link started.
  if (pathname.startsWith("/login") && pathname !== "/login/set-password") {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }

  if (pathname.startsWith("/admin") && role !== "admin") {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }

  return supabaseResponse;
}
